### ISSUE TITLE
Diego: Proposed changes to Architecture diagram

### ISSUE THREAD

**Issue by kaliask** [cloudfoundry/diego-design-notes#35]
I suggest to make a change architecture to diagram

It is  not clear that the consul-agent   inside the consul (box on the left handside of the diagram)  is running in the server mode and there is a consul-agent running inside each of the cells in  the client mode. The consul agent inside the cell are regularly communicating with consul server informing their status and joining/leaving the cluster.  Having consul-agent in cell box and an arrow going to consul server will make it very clear.  

I also pulled up an architecture diagram from Consul GitHub repository which shows this in detail and the communication protocols used between consul-agent client <-> server and server<->Server.  Attaching here for your reference.. Please consider adding to the documentation or a link to the page which has this diagram so reader have clear idea on what is going on.

file:///.file/id=6571367.6370534
file:///.file/id=6571367.6370577

**Comment by ematpl** [comment]
Thanks for the suggestion, @kaliask. As long as it doesn't get too crowded, I think something like that would be helpful. I don't see the files you attached, though.

Best,
Eric, CF Runtime Diego PM

**Comment by heyjcollins** [comment]
We've deprecated Consul so this issue is no longer relevant.
Going to close. Please comment and reopen if you believe it's important to do so.
