### ISSUE TITLE
Replacement for VCAP_APP_PORT

### ISSUE THREAD

**Issue by ssmoily** [cloudfoundry/diego-design-notes#36]
As per https://github.com/cloudfoundry/diego-design-notes/blob/master/migrating-to-diego.md#vcap_app_port , it appears that both PORT and CF_APP_PORT can be used as replacement for VCAP_APP_PORT . But while migrating a CF app to Diego I noticed that replacing VCAP_APP_PORT with `CF_APP_PORT` just makes the app crash, while replacing it with `PORT` seems to make it run fine. 
http://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#CF-INSTANCE-PORT seems to explain the difference correctly, and I think the diego deltas part of Diego migration readme should have the proper explanation.

**Comment by ematpl** [comment]
Thanks, @ssmoily! Fixed in https://github.com/cloudfoundry/diego-design-notes/commit/7dd883f5d99ed37b2c772b3f924a4f4be0894ed7.

**Comment by ssmoily** [comment]
👍
