### ISSUE TITLE
Converger missing from Brain in diagram

### ISSUE THREAD

**Issue by paulc4** [cloudfoundry/diego-design-notes#43]
Not sure why, but the Converger is missing from the diagram.  It is discussed in the notes, but is not on the diagram.

**Comment by emalm** [comment]
Thanks, @paulc4, the converger component was removed some time ago in [Diego v0.1481.0](https://github.com/cloudfoundry/diego-release/releases/tag/v0.1481.0), but we neglected to update the docs here.

**Comment by paulc4** [comment]
So which component performs this functionality now?

**Comment by emalm** [comment]
@paulc4: The BBS performs all the converger functionality now. The BBS already did most of the actual activity anyway in its single active instance, and the converger merely signaled it to perform the convergence operations periodically, so it made more sense to simplify the system to have the BBS do it all instead. Hope that helps!
